import companyLogo from "../../../../../../assets/images/IgniculussLogo.png";

export const printSelectedRow = (row) => {
  if (!row) return;

  // Open a new blank tab
  const printWindow = window.open("", "_blank");

  // Company details (Update with actual logo URL)
  // Replace with your logo URL
  // const companyName = "Your Company Name";

  // Write the printable HTML content
  printWindow.document.write(`
    <html>
      <head>
        <title>Buyer Details</title>
        <style>
          body { 
            font-family: Arial, sans-serif; 
            padding: 20px; 
            text-align: center; 
            background-color: #f8f9fa;
          }
          .container {
            max-width: 600px;
            margin: auto;
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
          }
          .logo {
            width: 120px;
            height: auto;
            margin-bottom: 10px;
          }
          h2 {
            color: #333;
            font-size: 24px;
            margin-bottom: 10px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
          }
          th {
            background-color: #007bff;
            color: white;
          }
          .footer {
            margin-top: 20px;
            font-size: 12px;
            color: #555;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <img src="${companyLogo}" alt="Company Logo" class="logo" />
          <div>
          <span style={{align:"left"}}>Heading Name</span>
          <table>
            <tr><th>Name</th><td>${row.name}</td></tr>
            <tr><th>Email</th><td>${row.email}</td></tr>
            <tr><th>Phone</th><td>${row.phone}</td></tr>
            <tr><th>Location</th><td>${row.location}</td></tr>
            <tr><th>Budget</th><td>${row.budget}</td></tr>
          </table>
          </div>
          <p class="footer">Generated by Igniculuss CRM System</p>
        </div>
        <script>
          setTimeout(() => {
            window.print();
            window.close();
          }, 500); // Delay ensures content is loaded before printing
        </script>
      </body>
    </html>
  `);

  // Close the document after writing to ensure it loads properly
  printWindow.document.close();
};
